.catalog:
  name: "Logstash"
  version: "6.1.1-rancher1"
  description: "Logstash: Process Any Data, From Any Source"
  questions:
    - variable: "collector_inputs"
      description: |
        Logstash collection tier inputs. These will be added
        directly to input { } section of logstash.conf
      label: "Logstash inputs"
      type: "multiline"
      required: true
      default: |
        udp {
          port => 5140
        }
    - variable: "indexer_filters"
      description: |
        Logstash indexing tier filters. These will be added
        directly to filter { } section of logstash.conf
      label: "Logstash filters"
      type: "multiline"
      required: false
      default: |
      grok {
        match => { "message" => "<%{POSINT:syslog_pri}>%{DATA:syslog_timestamp} %{SYSLOGHOST:syslog_host} %{DATA:syslog_program}\[%{NUMBER:syslog_
          pid}\]\: %{GREEDYDATA:syslog_message}" }
        }
        date {
          match => [ "syslog_timestamp", "yyyy:MM:dd-HH:mm:ss" ]
        }
        kv {
          source => "syslog_message"
        }
        mutate {
          replace => [ "type", "%{syslog_program}" ]
          remove_field  => [ "syslog_message", "syslog_timestamp" ]
        }
        translate {
          field => "srcip"
          destination => "maliciousIP"
          dictionary_path => '/opt/logstash/AlienVaultIP.yaml'
        }

        if [type] == "httpproxy" {
          grok { match => { "url" => "(?<protocol>https?)://%{IPORHOST:url_domain}/" } }

      }
    - variable: "indexer_outputs"
      description: |
        Logstash indexing tier outputs. These will be added
        directly to output { } section of logstash.conf
      label: "Logstash outputs"
      type: "multiline"
      required: true
      default: |
        elasticsearch {
          hosts => ["elasticsearch.rancher.internal:9200"]
        }
        stdout {
          codec => rubydebug
        }
    - variable: "elasticsearch_link"
      description: |
        stack/service link or external service link to elasticsearch
        cluster.
      label: "Elasticsearch stack/service"
      default: "es-cluster/es-client"
      required: true
      type: "service"
logstash-indexer:
  metadata:
    logstash:
      inputs: |
        redis {
          host => "redis.rancher.internal"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }
      filters: |
        ${indexer_filters}
      outputs: |
        ${indexer_outputs}
logstash-collector:
  metadata:
    logstash:
      inputs: |
        ${collector_inputs}
      outputs: |
        redis {
          host => "redis.rancher.internal"
          port => "6379"
          data_type => "list"
          key => "logstash"
        }
