version: '2'
services:
    openshift:
      image: llparse/openshift-origin:v1.2.1
      command: bootstrap_master
      labels:
        io.rancher.container.agent.role: environmentAdmin
        io.rancher.container.create_agent: 'true'
        io.rancher.container.dns: 'true'
        io.rancher.container.pull_image: always
        io.rancher.scheduler.affinity:host_label_ne: nopods=true
        io.rancher.scheduler.affinity:host_label_soft: openshift=true
      environment:
        KUBECONFIG: /etc/origin/master/admin.kubeconfig
        RANCHER_DEBUG: "true"
        CREATE_EXAMPLES: "true"
        CREATE_ROUTER: "true"
        CREATE_REGISTRY: "true"
      ports:
      - 8443:8443/tcp
      privileged: true
      volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    
    docker-config:
      image: llparse/openshift-origin:v1.2.1
      command: configure_docker
      labels:
        io.rancher.container.agent.role: environmentAdmin
        io.rancher.container.create_agent: 'true'
        io.rancher.container.start_once: 'true'
        io.rancher.scheduler.global: "true"
        io.rancher.scheduler.affinity:host_label_ne: nopods=true
      links:
      - openshift:openshift
      environment:
        KUBECONFIG: /etc/origin/master/admin.kubeconfig
        RANCHER_DEBUG: "true"
        CREATE_REGISTRY: "true"
      volumes:
      - /etc/docker/certs.d:/etc/docker/certs.d
