.catalog:
  name: OpenShift under Kubernetes
  version: v1.2.4-rancher9
  description: Rancher Kubernetes OpenShift service
  minimum_rancher_version: v1.0.1

openshift:
    health_check:
        request_line: GET /healthz HTTP/1.0
        port: 8443
        interval: 2000
        response_timeout: 2000
        unhealthy_threshold: 3
        healthy_threshold: 2
    retain_ip: true

