logstash-indexer-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  labels:
    io.rancher.container.hostname_override: container_name
redis:
  restart: always
  tty: true
  image: redis:alpine
  stdin_open: true
  labels:
    io.rancher.container.hostname_override: container_name
logstash-indexer:
  restart: always
  tty: true
  volumes_from:
  - logstash-indexer-config
  volumes:
  - /home/bsharin/elk/logstash/AlienVaultIP.yaml:/opt/logstash/AlienVaultIP.yaml
  - /home/bsharin/elk/logstash/dshield.txt:/opt/logstash/dshield.txt
  - /home/bsharin/elk/logstash/aws.txt:/opt/logstash/aws.txt
  - /home/bsharin/elk/logstash/spamhaus.txt:/opt/logstash/spamhaus.txt
  - /home/bsharin/elk/logstash/binarydefense.yaml:/opt/logstash/binarydefense.yaml
  command:
  - logstash
  - -f
  - /etc/logstash
  image: 10.0.211.103:6000/logstash-oss:6.1.2
  links:
  - redis:redis
  external_links:
  - ${elasticsearch_link}:elasticsearch1
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-indexer-config
    io.rancher.container.hostname_override: container_name
logstash-collector-config:
  restart: always
  image: rancher/logstash-config:v0.2.0
  labels:
    io.rancher.container.hostname_override: container_name
logstash-collector:
  restart: always
  tty: true
  links:
  - redis:redis
  ports:
  - "514:514/udp"
  volumes_from:
  - logstash-collector-config
  command:
  - logstash
  - -f
  - /etc/logstash
  image: 10.0.211.103:6000/logstash-oss:6.1.2
  stdin_open: true
  labels:
    io.rancher.sidekicks: logstash-collector-config
    io.rancher.container.hostname_override: container_name
